### ISSUE TITLE
Make a new release to include the last fix

### ISSUE THREAD

**Issue by Alaanor** [bekker/hangeul-rs#5]
I found a bug and I was about to make a PR. While doing so, I also checked for past PR and saw this was already fixed in https://github.com/bekker/hangeul-rs/pull/4. Unfortunately no release on crate.io was done since that fix.

On the meantime I could fix it on my side by telling cargo to use the rev e750463 but it would be nice if a release was made :)

**Comment by bekker** [comment]
I just made a new release 0.3.0, let me know if there is any issues :) Thanks.
