### ISSUE TITLE
ㅋ's Choseong enum is written as Kiyeok

### ISSUE THREAD

**Issue by asdfer-1234** [bekker/hangeul-rs#6]
`model` module's Jongseong `enum`'s `Kieuk`is written correctly, however Choseong `enum` has `Kiyeok`.

**Comment by asdfer-1234** [comment]
Is this error going to be kept for backwards compatibility reasons?

**Comment by bekker** [comment]
There seems to be no reliable way to alias enum values in Rust - none that I know of.

Still this error should be fixed. so I gave up the compatibility and bumped up the version.

Thanks.

러스트에는 enum alias를 예쁘게 할 수 있는 방법이 없어서 하위호환성을 유지하기가 힘들어 보이네요.

하지만 스펠링 틀린 건 고쳐야하긴 해서..

하위호환성 포기하고 버전업하겠습니다.

감사합니다.

**Comment by bekker** [comment]
Fixed and published 0.4.0
